### ISSUE TITLE
canceled function still finishes after timeout

### ISSUE THREAD

**Issue by teebu** [magicdawn/promise.timeout#7]
The expected result is to cancel the test(), without outputting 'test end'.

```
var ptimeout = require('promise.timeout')
const delay = ms => new Promise(_ => setTimeout(_, ms))


// a function will cost 20ms
async function test() {
  console.log('test start')
  await delay(2000)
  console.log('test end')
}

let x = ptimeout(test, 100)

async function run() {
  try {
    await x()
  } catch (e) {
    console.log('timed out')
    await delay(1000)
    console.log(e)
    return 'error'
  }
}

run()
```

**Comment by magicdawn** [comment]
u can implement your own `cancel` logic, using `onCancel`

```js
var ptimeout = require('promise.timeout')
const delay = ms => new Promise(_ => setTimeout(_, ms))


// a function will cost 20ms
async function test(onCancel) {
  let canceled = false
  onCancel && onCancel(() => {
    canceled = true
  })

  console.log('test start')
  await delay(2000)

  if(canceled) return
  console.log('test end')
}

let x = ptimeout(test, 100)

async function run() {
  try {
    await x()
  } catch (e) {
    console.log('timed out')
    await delay(1000)
    console.log(e)
    return 'error'
  }
}

run()
```

-------

- A library does not know how to cancel a function, but the developer can.
- onCancel is passed by ptimeout, and let u have a chance to register a custom cancel logic
when timeout reached, the registered logic will be called. e.g (set a canceled flag / http_request.abort / close some connection etc)

**Comment by magicdawn** [comment]
planed switch to AbortController before, but it's more complex.

- pitmeout pass an `abortController` instanceof `AbortController` as the last argument to the function passed to ptimeout
- the function check if an abortController is passed. use `abortController.signal.onabort = function(){ /* cancel logic */ }`
- it's almost same to `onCancel`, but need a `abort-controller` dependency.

**Comment by magicdawn** [comment]
- https://github.com/magicdawn/promise.timeout#oncancel
- https://github.com/magicdawn/promise.timeout#a-think-oncancel-like-the-abortcontroller

**Comment by teebu** [comment]
If I have multiple things happening in the function, this cancel doesn't really handle that.

```
var ptimeout = require('promise.timeout')
const delay = ms => new Promise(_ => setTimeout(_, ms))


async function test(onCancel) {
  let canceled = false
  onCancel && onCancel(() => {
    canceled = true
  })

  console.log('test start')
  await delay(2000)

  if(canceled) return
  console.log('test end 1')

  await delay(2000)
  console.log('test end 2')
}

let x = ptimeout(test, 2500, true)

async function run() {
  try {
    await x()
  } catch (e) {
    console.log('timed out')
    await delay(1000)
    console.log(e)
    return 'error'
  }
}

run()
```


I've done some more research, not sure if still true, but canceling a promise is a difficult task with current versions of nodejs. https://stackoverflow.com/questions/30233302/promise-is-it-possible-to-force-cancel-a-promise

I know bluebird has that ability, http://bluebirdjs.com/docs/api/timeout.html but it doesn't work with async/await.
